target("mainan")
    set_kind("binary")
    add_files("main.cpp", "uji/lingkungan_ekosistem.cu")
    add_includedirs(".")
    set_languages("c++17")
    add_syslinks("gdi32", "user32", "ws2_32", "shell32")
    add_links("cudart")

target("uji_fase1")
    set_kind("binary")
    add_files("uji/uji_fase1_kognisi_v3.cu")
    add_includedirs(".")
    set_languages("c++17")
    add_links("cudart")

