target("mainan")
    set_kind("binary")
    add_files("main.cpp", "gpu_mind.cu")
    set_languages("c++17")
    add_syslinks("gdi32", "user32", "ws2_32", "shell32")
    add_links("cudart")
    -- add_linkdirs("C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v13.3/lib/x64")
    -- add_includedirs("C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v13.3/include")
    add_linkdirs("C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v13.1/lib/x64")
    add_includedirs("C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v13.1/include")
